# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/discovery/v1/discovery.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/discovery/v1/discovery.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"proto/discovery/v1/discovery.proto\x12\x12proto.discovery.v1\"\x11\n\x0fGatewaysRequest\"A\n\x10GatewaysResponse\x12-\n\x08gateways\x18\x01 \x03(\x0b\x32\x1b.proto.discovery.v1.Gateway\"i\n\x07Gateway\x12\x17\n\x0f\x63ontrol_address\x18\x01 \x01(\t\x12\x14\n\x0c\x64\x61ta_address\x18\x02 \x01(\t\x12\x15\n\rprobe_address\x18\x03 \x01(\t\x12\x18\n\x10\x61llow_interfaces\x18\x04 \x03(\x04\"\x1e\n\x1cHiddenSegmentServicesRequest\"\xa9\x01\n\x1dHiddenSegmentServicesResponse\x12=\n\x06lookup\x18\x01 \x03(\x0b\x32-.proto.discovery.v1.HiddenSegmentLookupServer\x12I\n\x0cregistration\x18\x02 \x03(\x0b\x32\x33.proto.discovery.v1.HiddenSegmentRegistrationServer\",\n\x19HiddenSegmentLookupServer\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"2\n\x1fHiddenSegmentRegistrationServer\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t2\xeb\x01\n\x10\x44iscoveryService\x12W\n\x08Gateways\x12#.proto.discovery.v1.GatewaysRequest\x1a$.proto.discovery.v1.GatewaysResponse\"\x00\x12~\n\x15HiddenSegmentServices\x12\x30.proto.discovery.v1.HiddenSegmentServicesRequest\x1a\x31.proto.discovery.v1.HiddenSegmentServicesResponse\"\x00\x42\x31Z/github.com/scionproto/scion/pkg/proto/discoveryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.discovery.v1.discovery_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/scionproto/scion/pkg/proto/discovery'
  _globals['_GATEWAYSREQUEST']._serialized_start=58
  _globals['_GATEWAYSREQUEST']._serialized_end=75
  _globals['_GATEWAYSRESPONSE']._serialized_start=77
  _globals['_GATEWAYSRESPONSE']._serialized_end=142
  _globals['_GATEWAY']._serialized_start=144
  _globals['_GATEWAY']._serialized_end=249
  _globals['_HIDDENSEGMENTSERVICESREQUEST']._serialized_start=251
  _globals['_HIDDENSEGMENTSERVICESREQUEST']._serialized_end=281
  _globals['_HIDDENSEGMENTSERVICESRESPONSE']._serialized_start=284
  _globals['_HIDDENSEGMENTSERVICESRESPONSE']._serialized_end=453
  _globals['_HIDDENSEGMENTLOOKUPSERVER']._serialized_start=455
  _globals['_HIDDENSEGMENTLOOKUPSERVER']._serialized_end=499
  _globals['_HIDDENSEGMENTREGISTRATIONSERVER']._serialized_start=501
  _globals['_HIDDENSEGMENTREGISTRATIONSERVER']._serialized_end=551
  _globals['_DISCOVERYSERVICE']._serialized_start=554
  _globals['_DISCOVERYSERVICE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
