# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.hidden_segment.v1 import hidden_segment_pb2 as proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/hidden_segment/v1/hidden_segment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HiddenSegmentRegistrationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HiddenSegmentRegistration = channel.unary_unary(
                '/proto.hidden_segment.v1.HiddenSegmentRegistrationService/HiddenSegmentRegistration',
                request_serializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentRegistrationRequest.SerializeToString,
                response_deserializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentRegistrationResponse.FromString,
                _registered_method=True)


class HiddenSegmentRegistrationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HiddenSegmentRegistration(self, request, context):
        """HiddenSegmentRegistration registers hidden segments at the remote.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HiddenSegmentRegistrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HiddenSegmentRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.HiddenSegmentRegistration,
                    request_deserializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentRegistrationRequest.FromString,
                    response_serializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentRegistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.hidden_segment.v1.HiddenSegmentRegistrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.hidden_segment.v1.HiddenSegmentRegistrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HiddenSegmentRegistrationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HiddenSegmentRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.hidden_segment.v1.HiddenSegmentRegistrationService/HiddenSegmentRegistration',
            proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentRegistrationRequest.SerializeToString,
            proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HiddenSegmentLookupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HiddenSegments = channel.unary_unary(
                '/proto.hidden_segment.v1.HiddenSegmentLookupService/HiddenSegments',
                request_serializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentsRequest.SerializeToString,
                response_deserializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentsResponse.FromString,
                _registered_method=True)


class HiddenSegmentLookupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HiddenSegments(self, request, context):
        """HiddenSegments returns all segments that match the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HiddenSegmentLookupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HiddenSegments': grpc.unary_unary_rpc_method_handler(
                    servicer.HiddenSegments,
                    request_deserializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentsRequest.FromString,
                    response_serializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.hidden_segment.v1.HiddenSegmentLookupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.hidden_segment.v1.HiddenSegmentLookupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HiddenSegmentLookupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HiddenSegments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.hidden_segment.v1.HiddenSegmentLookupService/HiddenSegments',
            proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentsRequest.SerializeToString,
            proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.HiddenSegmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuthoritativeHiddenSegmentLookupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuthoritativeHiddenSegments = channel.unary_unary(
                '/proto.hidden_segment.v1.AuthoritativeHiddenSegmentLookupService/AuthoritativeHiddenSegments',
                request_serializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.AuthoritativeHiddenSegmentsRequest.SerializeToString,
                response_deserializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.AuthoritativeHiddenSegmentsResponse.FromString,
                _registered_method=True)


class AuthoritativeHiddenSegmentLookupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AuthoritativeHiddenSegments(self, request, context):
        """HiddenSegments returns all segments that match the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthoritativeHiddenSegmentLookupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuthoritativeHiddenSegments': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthoritativeHiddenSegments,
                    request_deserializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.AuthoritativeHiddenSegmentsRequest.FromString,
                    response_serializer=proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.AuthoritativeHiddenSegmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.hidden_segment.v1.AuthoritativeHiddenSegmentLookupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.hidden_segment.v1.AuthoritativeHiddenSegmentLookupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthoritativeHiddenSegmentLookupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuthoritativeHiddenSegments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.hidden_segment.v1.AuthoritativeHiddenSegmentLookupService/AuthoritativeHiddenSegments',
            proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.AuthoritativeHiddenSegmentsRequest.SerializeToString,
            proto_dot_hidden__segment_dot_v1_dot_hidden__segment__pb2.AuthoritativeHiddenSegmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
