# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/control_plane/experimental/v1/seg_detached_extensions.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/control_plane/experimental/v1/seg_detached_extensions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAproto/control_plane/experimental/v1/seg_detached_extensions.proto\x12#proto.control_plane.experimental.v1\"J\n\x15\x45PICDetachedExtension\x12\x16\n\x0e\x61uth_hop_entry\x18\x01 \x01(\x0c\x12\x19\n\x11\x61uth_peer_entries\x18\x02 \x03(\x0c\x42\x42Z@github.com/scionproto/scion/pkg/proto/control_plane/experimentalb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.control_plane.experimental.v1.seg_detached_extensions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z@github.com/scionproto/scion/pkg/proto/control_plane/experimental'
  _globals['_EPICDETACHEDEXTENSION']._serialized_start=106
  _globals['_EPICDETACHEDEXTENSION']._serialized_end=180
# @@protoc_insertion_point(module_scope)
