# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/crypto/v1/signed.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/crypto/v1/signed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/crypto/v1/signed.proto\x12\x0fproto.crypto.v1\x1a\x1fgoogle/protobuf/timestamp.proto\";\n\rSignedMessage\x12\x17\n\x0fheader_and_body\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"\xc8\x01\n\x06Header\x12@\n\x13signature_algorithm\x18\x01 \x01(\x0e\x32#.proto.crypto.v1.SignatureAlgorithm\x12\x1b\n\x13verification_key_id\x18\x02 \x01(\x0c\x12-\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08metadata\x18\x04 \x01(\x0c\x12\x1e\n\x16\x61ssociated_data_length\x18\x05 \x01(\x05\"5\n\x15HeaderAndBodyInternal\x12\x0e\n\x06header\x18\x01 \x01(\x0c\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c*\xba\x01\n\x12SignatureAlgorithm\x12#\n\x1fSIGNATURE_ALGORITHM_UNSPECIFIED\x10\x00\x12)\n%SIGNATURE_ALGORITHM_ECDSA_WITH_SHA256\x10\x01\x12)\n%SIGNATURE_ALGORITHM_ECDSA_WITH_SHA384\x10\x02\x12)\n%SIGNATURE_ALGORITHM_ECDSA_WITH_SHA512\x10\x03\x42.Z,github.com/scionproto/scion/pkg/proto/cryptob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.crypto.v1.signed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/scionproto/scion/pkg/proto/crypto'
  _globals['_SIGNATUREALGORITHM']._serialized_start=402
  _globals['_SIGNATUREALGORITHM']._serialized_end=588
  _globals['_SIGNEDMESSAGE']._serialized_start=82
  _globals['_SIGNEDMESSAGE']._serialized_end=141
  _globals['_HEADER']._serialized_start=144
  _globals['_HEADER']._serialized_end=344
  _globals['_HEADERANDBODYINTERNAL']._serialized_start=346
  _globals['_HEADERANDBODYINTERNAL']._serialized_end=399
# @@protoc_insertion_point(module_scope)
