# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/control_plane/v1/cppki.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/control_plane/v1/cppki.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"proto/control_plane/v1/cppki.proto\x12\x16proto.control_plane.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x01\n\rChainsRequest\x12\x0e\n\x06isd_as\x18\x01 \x01(\x04\x12\x16\n\x0esubject_key_id\x18\x02 \x01(\x0c\x12\x38\n\x14\x61t_least_valid_until\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x38\n\x14\x61t_least_valid_since\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"?\n\x0e\x43hainsResponse\x12-\n\x06\x63hains\x18\x01 \x03(\x0b\x32\x1d.proto.control_plane.v1.Chain\")\n\x05\x43hain\x12\x0f\n\x07\x61s_cert\x18\x01 \x01(\x0c\x12\x0f\n\x07\x63\x61_cert\x18\x02 \x01(\x0c\"7\n\nTRCRequest\x12\x0b\n\x03isd\x18\x01 \x01(\r\x12\x0c\n\x04\x62\x61se\x18\x02 \x01(\x04\x12\x0e\n\x06serial\x18\x03 \x01(\x04\"\x1a\n\x0bTRCResponse\x12\x0b\n\x03trc\x18\x01 \x01(\x0c\"a\n\x11VerificationKeyID\x12\x0e\n\x06isd_as\x18\x01 \x01(\x04\x12\x16\n\x0esubject_key_id\x18\x02 \x01(\x0c\x12\x10\n\x08trc_base\x18\x03 \x01(\x04\x12\x12\n\ntrc_serial\x18\x04 \x01(\x04\x32\xc3\x01\n\x14TrustMaterialService\x12Y\n\x06\x43hains\x12%.proto.control_plane.v1.ChainsRequest\x1a&.proto.control_plane.v1.ChainsResponse\"\x00\x12P\n\x03TRC\x12\".proto.control_plane.v1.TRCRequest\x1a#.proto.control_plane.v1.TRCResponse\"\x00\x42\x35Z3github.com/scionproto/scion/pkg/proto/control_planeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.control_plane.v1.cppki_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/scionproto/scion/pkg/proto/control_plane'
  _globals['_CHAINSREQUEST']._serialized_start=96
  _globals['_CHAINSREQUEST']._serialized_end=267
  _globals['_CHAINSRESPONSE']._serialized_start=269
  _globals['_CHAINSRESPONSE']._serialized_end=332
  _globals['_CHAIN']._serialized_start=334
  _globals['_CHAIN']._serialized_end=375
  _globals['_TRCREQUEST']._serialized_start=377
  _globals['_TRCREQUEST']._serialized_end=432
  _globals['_TRCRESPONSE']._serialized_start=434
  _globals['_TRCRESPONSE']._serialized_end=460
  _globals['_VERIFICATIONKEYID']._serialized_start=462
  _globals['_VERIFICATIONKEYID']._serialized_end=559
  _globals['_TRUSTMATERIALSERVICE']._serialized_start=562
  _globals['_TRUSTMATERIALSERVICE']._serialized_end=757
# @@protoc_insertion_point(module_scope)
