# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.control_plane.v1 import cppki_pb2 as proto_dot_control__plane_dot_v1_dot_cppki__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/control_plane/v1/cppki_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrustMaterialServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chains = channel.unary_unary(
                '/proto.control_plane.v1.TrustMaterialService/Chains',
                request_serializer=proto_dot_control__plane_dot_v1_dot_cppki__pb2.ChainsRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_cppki__pb2.ChainsResponse.FromString,
                _registered_method=True)
        self.TRC = channel.unary_unary(
                '/proto.control_plane.v1.TrustMaterialService/TRC',
                request_serializer=proto_dot_control__plane_dot_v1_dot_cppki__pb2.TRCRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_cppki__pb2.TRCResponse.FromString,
                _registered_method=True)


class TrustMaterialServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chains(self, request, context):
        """Return the certificate chains that match the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TRC(self, request, context):
        """Return a specific TRC that matches the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrustMaterialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chains': grpc.unary_unary_rpc_method_handler(
                    servicer.Chains,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_cppki__pb2.ChainsRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_cppki__pb2.ChainsResponse.SerializeToString,
            ),
            'TRC': grpc.unary_unary_rpc_method_handler(
                    servicer.TRC,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_cppki__pb2.TRCRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_cppki__pb2.TRCResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.control_plane.v1.TrustMaterialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.control_plane.v1.TrustMaterialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrustMaterialService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chains(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.TrustMaterialService/Chains',
            proto_dot_control__plane_dot_v1_dot_cppki__pb2.ChainsRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_cppki__pb2.ChainsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TRC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.TrustMaterialService/TRC',
            proto_dot_control__plane_dot_v1_dot_cppki__pb2.TRCRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_cppki__pb2.TRCResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
