# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.control_plane.v1 import drkey_pb2 as proto_dot_control__plane_dot_v1_dot_drkey__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/control_plane/v1/drkey_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DRKeyInterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DRKeyLevel1 = channel.unary_unary(
                '/proto.control_plane.v1.DRKeyInterService/DRKeyLevel1',
                request_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyLevel1Request.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyLevel1Response.FromString,
                _registered_method=True)


class DRKeyInterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DRKeyLevel1(self, request, context):
        """Return the Level1Key that matches the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DRKeyInterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DRKeyLevel1': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeyLevel1,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyLevel1Request.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyLevel1Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.control_plane.v1.DRKeyInterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.control_plane.v1.DRKeyInterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DRKeyInterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DRKeyLevel1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.DRKeyInterService/DRKeyLevel1',
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyLevel1Request.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyLevel1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DRKeyIntraServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DRKeyIntraLevel1 = channel.unary_unary(
                '/proto.control_plane.v1.DRKeyIntraService/DRKeyIntraLevel1',
                request_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyIntraLevel1Request.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyIntraLevel1Response.FromString,
                _registered_method=True)
        self.DRKeyASHost = channel.unary_unary(
                '/proto.control_plane.v1.DRKeyIntraService/DRKeyASHost',
                request_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyASHostRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyASHostResponse.FromString,
                _registered_method=True)
        self.DRKeyHostAS = channel.unary_unary(
                '/proto.control_plane.v1.DRKeyIntraService/DRKeyHostAS',
                request_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostASRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostASResponse.FromString,
                _registered_method=True)
        self.DRKeyHostHost = channel.unary_unary(
                '/proto.control_plane.v1.DRKeyIntraService/DRKeyHostHost',
                request_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostHostRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostHostResponse.FromString,
                _registered_method=True)
        self.DRKeySecretValue = channel.unary_unary(
                '/proto.control_plane.v1.DRKeyIntraService/DRKeySecretValue',
                request_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeySecretValueRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeySecretValueResponse.FromString,
                _registered_method=True)


class DRKeyIntraServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DRKeyIntraLevel1(self, request, context):
        """Return the ASAS that matches the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DRKeyASHost(self, request, context):
        """Return the AS-Host that matches the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DRKeyHostAS(self, request, context):
        """Return the Host-AS that matches the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DRKeyHostHost(self, request, context):
        """Return the Host-Host that matches the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DRKeySecretValue(self, request, context):
        """Return the SecretValue that matches the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DRKeyIntraServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DRKeyIntraLevel1': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeyIntraLevel1,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyIntraLevel1Request.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyIntraLevel1Response.SerializeToString,
            ),
            'DRKeyASHost': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeyASHost,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyASHostRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyASHostResponse.SerializeToString,
            ),
            'DRKeyHostAS': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeyHostAS,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostASRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostASResponse.SerializeToString,
            ),
            'DRKeyHostHost': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeyHostHost,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostHostRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostHostResponse.SerializeToString,
            ),
            'DRKeySecretValue': grpc.unary_unary_rpc_method_handler(
                    servicer.DRKeySecretValue,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeySecretValueRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeySecretValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.control_plane.v1.DRKeyIntraService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.control_plane.v1.DRKeyIntraService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DRKeyIntraService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DRKeyIntraLevel1(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.DRKeyIntraService/DRKeyIntraLevel1',
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyIntraLevel1Request.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyIntraLevel1Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DRKeyASHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.DRKeyIntraService/DRKeyASHost',
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyASHostRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyASHostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DRKeyHostAS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.DRKeyIntraService/DRKeyHostAS',
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostASRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostASResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DRKeyHostHost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.DRKeyIntraService/DRKeyHostHost',
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostHostRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeyHostHostResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DRKeySecretValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.DRKeyIntraService/DRKeySecretValue',
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeySecretValueRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_drkey__pb2.DRKeySecretValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
