# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.control_plane.v1 import renewal_pb2 as proto_dot_control__plane_dot_v1_dot_renewal__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/control_plane/v1/renewal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChainRenewalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChainRenewal = channel.unary_unary(
                '/proto.control_plane.v1.ChainRenewalService/ChainRenewal',
                request_serializer=proto_dot_control__plane_dot_v1_dot_renewal__pb2.ChainRenewalRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_renewal__pb2.ChainRenewalResponse.FromString,
                _registered_method=True)


class ChainRenewalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChainRenewal(self, request, context):
        """RenewChain creates a chain from the chain request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChainRenewalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChainRenewal': grpc.unary_unary_rpc_method_handler(
                    servicer.ChainRenewal,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_renewal__pb2.ChainRenewalRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_renewal__pb2.ChainRenewalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.control_plane.v1.ChainRenewalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.control_plane.v1.ChainRenewalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChainRenewalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChainRenewal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.ChainRenewalService/ChainRenewal',
            proto_dot_control__plane_dot_v1_dot_renewal__pb2.ChainRenewalRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_renewal__pb2.ChainRenewalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
