# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/control_plane/v1/renewal.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/control_plane/v1/renewal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto.control_plane.v1 import cppki_pb2 as proto_dot_control__plane_dot_v1_dot_cppki__pb2
from proto.crypto.v1 import signed_pb2 as proto_dot_crypto_dot_v1_dot_signed__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$proto/control_plane/v1/renewal.proto\x12\x16proto.control_plane.v1\x1a\"proto/control_plane/v1/cppki.proto\x1a\x1cproto/crypto/v1/signed.proto\"i\n\x13\x43hainRenewalRequest\x12\x36\n\x0esigned_request\x18\x01 \x01(\x0b\x32\x1e.proto.crypto.v1.SignedMessage\x12\x1a\n\x12\x63ms_signed_request\x18\x02 \x01(\x0c\"&\n\x17\x43hainRenewalRequestBody\x12\x0b\n\x03\x63sr\x18\x01 \x01(\x0c\"l\n\x14\x43hainRenewalResponse\x12\x37\n\x0fsigned_response\x18\x01 \x01(\x0b\x32\x1e.proto.crypto.v1.SignedMessage\x12\x1b\n\x13\x63ms_signed_response\x18\x02 \x01(\x0c\"H\n\x18\x43hainRenewalResponseBody\x12,\n\x05\x63hain\x18\x01 \x01(\x0b\x32\x1d.proto.control_plane.v1.Chain2\x82\x01\n\x13\x43hainRenewalService\x12k\n\x0c\x43hainRenewal\x12+.proto.control_plane.v1.ChainRenewalRequest\x1a,.proto.control_plane.v1.ChainRenewalResponse\"\x00\x42\x35Z3github.com/scionproto/scion/pkg/proto/control_planeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.control_plane.v1.renewal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/scionproto/scion/pkg/proto/control_plane'
  _globals['_CHAINRENEWALREQUEST']._serialized_start=130
  _globals['_CHAINRENEWALREQUEST']._serialized_end=235
  _globals['_CHAINRENEWALREQUESTBODY']._serialized_start=237
  _globals['_CHAINRENEWALREQUESTBODY']._serialized_end=275
  _globals['_CHAINRENEWALRESPONSE']._serialized_start=277
  _globals['_CHAINRENEWALRESPONSE']._serialized_end=385
  _globals['_CHAINRENEWALRESPONSEBODY']._serialized_start=387
  _globals['_CHAINRENEWALRESPONSEBODY']._serialized_end=459
  _globals['_CHAINRENEWALSERVICE']._serialized_start=462
  _globals['_CHAINRENEWALSERVICE']._serialized_end=592
# @@protoc_insertion_point(module_scope)
