# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.control_plane.v1 import seg_pb2 as proto_dot_control__plane_dot_v1_dot_seg__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/control_plane/v1/seg_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SegmentLookupServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Segments = channel.unary_unary(
                '/proto.control_plane.v1.SegmentLookupService/Segments',
                request_serializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsResponse.FromString,
                _registered_method=True)


class SegmentLookupServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Segments(self, request, context):
        """Segments returns all segments that match the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SegmentLookupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Segments': grpc.unary_unary_rpc_method_handler(
                    servicer.Segments,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.control_plane.v1.SegmentLookupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.control_plane.v1.SegmentLookupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SegmentLookupService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Segments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.SegmentLookupService/Segments',
            proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SegmentRegistrationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SegmentsRegistration = channel.unary_unary(
                '/proto.control_plane.v1.SegmentRegistrationService/SegmentsRegistration',
                request_serializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRegistrationRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRegistrationResponse.FromString,
                _registered_method=True)


class SegmentRegistrationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SegmentsRegistration(self, request, context):
        """SegmentsRegistration registers segments at the remote.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SegmentRegistrationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SegmentsRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.SegmentsRegistration,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRegistrationRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRegistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.control_plane.v1.SegmentRegistrationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.control_plane.v1.SegmentRegistrationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SegmentRegistrationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SegmentsRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.SegmentRegistrationService/SegmentsRegistration',
            proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRegistrationRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_seg__pb2.SegmentsRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SegmentCreationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Beacon = channel.unary_unary(
                '/proto.control_plane.v1.SegmentCreationService/Beacon',
                request_serializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.BeaconRequest.SerializeToString,
                response_deserializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.BeaconResponse.FromString,
                _registered_method=True)


class SegmentCreationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Beacon(self, request, context):
        """Beacon sends a beacon to the remote.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SegmentCreationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Beacon': grpc.unary_unary_rpc_method_handler(
                    servicer.Beacon,
                    request_deserializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.BeaconRequest.FromString,
                    response_serializer=proto_dot_control__plane_dot_v1_dot_seg__pb2.BeaconResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.control_plane.v1.SegmentCreationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.control_plane.v1.SegmentCreationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SegmentCreationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Beacon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.control_plane.v1.SegmentCreationService/Beacon',
            proto_dot_control__plane_dot_v1_dot_seg__pb2.BeaconRequest.SerializeToString,
            proto_dot_control__plane_dot_v1_dot_seg__pb2.BeaconResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
