# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/control_plane/v1/svc_resolution.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/control_plane/v1/svc_resolution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+proto/control_plane/v1/svc_resolution.proto\x12\x16proto.control_plane.v1\"\x1a\n\x18ServiceResolutionRequest\"\xc8\x01\n\x19ServiceResolutionResponse\x12U\n\ntransports\x18\x01 \x03(\x0b\x32\x41.proto.control_plane.v1.ServiceResolutionResponse.TransportsEntry\x1aT\n\x0fTransportsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.proto.control_plane.v1.Transport:\x02\x38\x01\"\x1c\n\tTransport\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\tB5Z3github.com/scionproto/scion/pkg/proto/control_planeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.control_plane.v1.svc_resolution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/scionproto/scion/pkg/proto/control_plane'
  _globals['_SERVICERESOLUTIONRESPONSE_TRANSPORTSENTRY']._loaded_options = None
  _globals['_SERVICERESOLUTIONRESPONSE_TRANSPORTSENTRY']._serialized_options = b'8\001'
  _globals['_SERVICERESOLUTIONREQUEST']._serialized_start=71
  _globals['_SERVICERESOLUTIONREQUEST']._serialized_end=97
  _globals['_SERVICERESOLUTIONRESPONSE']._serialized_start=100
  _globals['_SERVICERESOLUTIONRESPONSE']._serialized_end=300
  _globals['_SERVICERESOLUTIONRESPONSE_TRANSPORTSENTRY']._serialized_start=216
  _globals['_SERVICERESOLUTIONRESPONSE_TRANSPORTSENTRY']._serialized_end=300
  _globals['_TRANSPORT']._serialized_start=302
  _globals['_TRANSPORT']._serialized_end=330
# @@protoc_insertion_point(module_scope)
