# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/gateway/v1/control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'proto/gateway/v1/control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/gateway/v1/control.proto\x12\x10proto.gateway.v1\"L\n\x0e\x43ontrolRequest\x12/\n\x05probe\x18\x01 \x01(\x0b\x32\x1e.proto.gateway.v1.ProbeRequestH\x00\x42\t\n\x07request\"O\n\x0f\x43ontrolResponse\x12\x30\n\x05probe\x18\x01 \x01(\x0b\x32\x1f.proto.gateway.v1.ProbeResponseH\x00\x42\n\n\x08response\"0\n\x0cProbeRequest\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"1\n\rProbeResponse\x12\x12\n\nsession_id\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42/Z-github.com/scionproto/scion/pkg/proto/gatewayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.gateway.v1.control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/scionproto/scion/pkg/proto/gateway'
  _globals['_CONTROLREQUEST']._serialized_start=52
  _globals['_CONTROLREQUEST']._serialized_end=128
  _globals['_CONTROLRESPONSE']._serialized_start=130
  _globals['_CONTROLRESPONSE']._serialized_end=209
  _globals['_PROBEREQUEST']._serialized_start=211
  _globals['_PROBEREQUEST']._serialized_end=259
  _globals['_PROBERESPONSE']._serialized_start=261
  _globals['_PROBERESPONSE']._serialized_end=310
# @@protoc_insertion_point(module_scope)
